implementado modulo de disponibilidade
AGES-PUCRS/barbadehomem-admin pull request #7
Opened 2020-06-03 20:15 UTC by liveki

2020-06-11 18:17 UTC, aranha reviewed
show, funcionando 100%

2020-06-11 18:19 UTC, aranha approved these changes

2020-06-12 20:53 UTC, gmenti requested changes

2020-06-12 20:53 UTC, gmenti commented on src/App.js
> +    // authProvider={authProvider}
Descomentar essas 2 linhas responsáveis pela autenticação no app

2020-06-12 21:00 UTC, merged