T33 anotacoes barbeiros e clientes
AGES-PUCRS/barbadehomem-admin pull request #8
Opened 2020-06-05 23:22 UTC by liveki

2020-06-11 18:33 UTC, aranha approved these changes

2020-06-12 20:51 UTC, gmenti commented on src/App.js
> +    // authProvider={authProvider}
Pq está comentada a autenticação?

2020-06-12 20:52 UTC, gmenti requested changes

2020-06-12 20:52 UTC, gmenti commented on src/App.js
> +    // authProvider={authProvider}
Descomentar essas 2 linhas responsáveis por ativa a autenticação no app

2020-06-12 20:52 UTC, gmenti commented on src/resources/Appointment/AppointmentList.js
> +  console.log(props.record);
Remover log

2020-06-12 21:00 UTC, merged